#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : OpenColorIO
Version  : 2.4.0
Release  : 43
URL      : https://github.com/imageworks/OpenColorIO/archive/v2.4.0/OpenColorIO-2.4.0.tar.gz
Source0  : https://github.com/imageworks/OpenColorIO/archive/v2.4.0/OpenColorIO-2.4.0.tar.gz
Summary  : @PROJECT_DESCRIPTION@
Group    : Development/Tools
License  : BSD-3-Clause
Requires: OpenColorIO-bin = %{version}-%{release}
Requires: OpenColorIO-data = %{version}-%{release}
Requires: OpenColorIO-lib = %{version}-%{release}
Requires: OpenColorIO-license = %{version}-%{release}
BuildRequires : Imath-dev
BuildRequires : buildreq-cmake
BuildRequires : doxygen
BuildRequires : expat-dev
BuildRequires : freeglut-dev
BuildRequires : glew-dev
BuildRequires : lcms2-dev
BuildRequires : openexr-dev
BuildRequires : openjdk
BuildRequires : openjdk-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(Imath)
BuildRequires : pkgconfig(expat)
BuildRequires : pkgconfig(lcms2)
BuildRequires : pkgconfig(minizip)
BuildRequires : pkgconfig(yaml-cpp)
BuildRequires : pypi(markupsafe)
BuildRequires : pypi(pybind11)
BuildRequires : pystring-dev
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : yaml-cpp-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
These files ship with Mari, and are *not* required to be manually installed.
They are provided as a reference example of using the OCIO API to create a GPU
monitor implementation in python.

%package bin
Summary: bin components for the OpenColorIO package.
Group: Binaries
Requires: OpenColorIO-data = %{version}-%{release}
Requires: OpenColorIO-license = %{version}-%{release}

%description bin
bin components for the OpenColorIO package.


%package data
Summary: data components for the OpenColorIO package.
Group: Data

%description data
data components for the OpenColorIO package.


%package dev
Summary: dev components for the OpenColorIO package.
Group: Development
Requires: OpenColorIO-lib = %{version}-%{release}
Requires: OpenColorIO-bin = %{version}-%{release}
Requires: OpenColorIO-data = %{version}-%{release}
Provides: OpenColorIO-devel = %{version}-%{release}
Requires: OpenColorIO = %{version}-%{release}

%description dev
dev components for the OpenColorIO package.


%package lib
Summary: lib components for the OpenColorIO package.
Group: Libraries
Requires: OpenColorIO-data = %{version}-%{release}
Requires: OpenColorIO-license = %{version}-%{release}

%description lib
lib components for the OpenColorIO package.


%package license
Summary: license components for the OpenColorIO package.
Group: Default

%description license
license components for the OpenColorIO package.


%prep
%setup -q -n OpenColorIO-2.4.0
cd %{_builddir}/OpenColorIO-2.4.0
pushd ..
cp -a OpenColorIO-2.4.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1738630089
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1738630089
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/OpenColorIO
cp %{_builddir}/OpenColorIO-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/OpenColorIO/7ac1e3369e577b103d4a840ae465ae08582f7429 || :
cp %{_builddir}/OpenColorIO-%{version}/vendor/openfx/Support/LICENSE %{buildroot}/usr/share/package-licenses/OpenColorIO/b1193cfe49ec6be09a6d34cf85a341d403c04a23 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/python3.13/site-packages/PyOpenColorIO/__init__.py

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/ocioarchive
/V3/usr/bin/ociobakelut
/V3/usr/bin/ociocheck
/V3/usr/bin/ociochecklut
/V3/usr/bin/ocioconvert
/V3/usr/bin/ociocpuinfo
/V3/usr/bin/ociodisplay
/V3/usr/bin/ociolutimage
/V3/usr/bin/ociomakeclf
/V3/usr/bin/ocioperf
/V3/usr/bin/ociowrite
/usr/bin/ocioarchive
/usr/bin/ociobakelut
/usr/bin/ociocheck
/usr/bin/ociochecklut
/usr/bin/ocioconvert
/usr/bin/ociocpuinfo
/usr/bin/ociodisplay
/usr/bin/ociolutimage
/usr/bin/ociomakeclf
/usr/bin/ocioperf
/usr/bin/ociowrite

%files data
%defattr(-,root,root,-)
/usr/share/ocio/setup_ocio.sh

%files dev
%defattr(-,root,root,-)
/usr/include/OpenColorIO/OpenColorABI.h
/usr/include/OpenColorIO/OpenColorAppHelpers.h
/usr/include/OpenColorIO/OpenColorIO.h
/usr/include/OpenColorIO/OpenColorTransforms.h
/usr/include/OpenColorIO/OpenColorTypes.h
/usr/include/OpenColorIO/imageioapphelpers/imageio.h
/usr/include/OpenColorIO/oglapphelpers/glsl.h
/usr/include/OpenColorIO/oglapphelpers/oglapp.h
/usr/lib64/cmake/OpenColorIO/OpenColorIOConfig.cmake
/usr/lib64/cmake/OpenColorIO/OpenColorIOConfigVersion.cmake
/usr/lib64/cmake/OpenColorIO/OpenColorIOTargets-relwithdebinfo.cmake
/usr/lib64/cmake/OpenColorIO/OpenColorIOTargets.cmake
/usr/lib64/libOpenColorIO.so
/usr/lib64/pkgconfig/OpenColorIO.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libOpenColorIO.so.2.4.0
/V3/usr/lib64/python3.13/site-packages/PyOpenColorIO/PyOpenColorIO.so
/usr/lib64/libOpenColorIO.so.2.4
/usr/lib64/libOpenColorIO.so.2.4.0
/usr/lib64/python3.13/site-packages/PyOpenColorIO/PyOpenColorIO.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/OpenColorIO/7ac1e3369e577b103d4a840ae465ae08582f7429
/usr/share/package-licenses/OpenColorIO/b1193cfe49ec6be09a6d34cf85a341d403c04a23
